#!/usr/bin/env bash
# Stitch the SI subsection fragments into a single file in the order
#   gen → pes → kinetics → shared → seeds → params
# Order matches the desired SI section sequence; LaTeX numbers
# \subsection{...} in document order, so the rendered SI numbering will be:
#   SI-1 Generative loop
#   SI-2 PES loop
#   SI-3 Kinetics
#   SI-4 Shared machinery
#   SI-5 Seeds
#   SI-6 Parameter reference
#
# Usage:
#   ./merge_si.sh                          # → si_merged.tex
#   ./merge_si.sh path/to/output.tex       # → custom output path
#
# Run from the report/ directory (or any directory; uses script location).

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${1:-$HERE/si_merged.tex}"

FILES=(
    "si2_generative_loop.tex"
    "si1_pes_loop.tex"
    "si3_kinetics.tex"
    "si6_shared_machinery.tex"
    "si4_seeds.tex"
    "si_parameters.tex"
)

# Sanity: refuse to overwrite if any source file is missing.
for f in "${FILES[@]}"; do
    if [[ ! -f "$HERE/$f" ]]; then
        echo "merge_si.sh: missing source $HERE/$f" >&2
        exit 1
    fi
done

{
    echo "% ============================================================================"
    echo "% Stitched Supplementary Information"
    echo "% Generated by merge_si.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
    echo "% Section order: generative → PES → kinetics → shared → seeds → parameters"
    echo "% ============================================================================"
    echo ""
    for f in "${FILES[@]}"; do
        echo "% --- begin $f ---"
        cat "$HERE/$f"
        echo ""
        echo "% --- end $f ---"
        echo ""
    done
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
